# Generated by Django 4.2.20 on 2025-04-03 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='case_insensitive', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLogbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logbook_date', models.DateField()),
                ('total_miles_driving_today', models.FloatField(default=0)),
                ('mileage_covered_today', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LogbookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('', 'select item'), ('off-duty', 'Off Duty'), ('driving', 'Driving'), ('on-duty-not-driving', 'On Duty (not driving)'), ('sleeper-berth', 'Sleeper Berth')], max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StopRest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_location', models.JSONField()),
                ('stop_type', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(db_collation='case_insensitive', max_length=100, unique=True)),
                ('trailer_number', models.CharField(db_collation='case_insensitive', max_length=100, unique=True)),
                ('truck_assigned', models.BooleanField(default=False)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logbook.carrier')),
            ],
        ),
        migrations.CreateModel(
            name='TripDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.JSONField()),
                ('pickup_location', models.JSONField()),
                ('dropoff_location', models.JSONField()),
                ('cycle_used', models.CharField(max_length=100)),
                ('trip_start_date', models.DateField(null=True)),
                ('trip_end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logbook.carrier')),
            ],
        ),
    ]
