# Generated by Django 4.2.20 on 2025-03-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.JSONField()),
                ('pickup_location', models.JSONField()),
                ('dropoff_location', models.JSONField()),
                ('cycle_used', models.CharField(max_length=100)),
                ('trip_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TripItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('', 'select item'), ('off-duty', 'Off Duty'), ('driving', 'Driving'), ('on-duty-not-driving', 'On Duty (not driving)')], max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('trip_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logbook.tripdetail')),
            ],
        ),
        migrations.CreateModel(
            name='StopRest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_location', models.JSONField()),
                ('remarks', models.CharField(max_length=255)),
                ('trip_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logbook.tripdetail')),
            ],
        ),
    ]
