# Generated by Django 4.2.20 on 2025-04-03 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetail',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logbook.truck'),
        ),
        migrations.AddField(
            model_name='stoprest',
            name='trip_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logbook.tripdetail'),
        ),
        migrations.AddField(
            model_name='logbookitem',
            name='driver_logbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logbook.driverlogbook'),
        ),
        migrations.AddField(
            model_name='driverlogbook',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrier',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrier_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='driverlogbook',
            unique_together={('driver', 'logbook_date')},
        ),
    ]
