# Generated by Django 4.2.20 on 2025-03-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetail',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
