# Generated by Django 4.2.20 on 2025-03-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_tripdetail_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stoprest',
            old_name='remarks',
            new_name='stop_type',
        ),
        migrations.AddField(
            model_name='stoprest',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='stoprest',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
