# Generated by Django 4.2.20 on 2025-03-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_rename_remarks_stoprest_stop_type_stoprest_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripitem',
            name='item_type',
            field=models.CharField(choices=[('', 'select item'), ('off-duty', 'Off Duty'), ('driving', 'Driving'), ('on-duty-not-driving', 'On Duty (not driving)'), ('sleeper-berth', 'Sleeper Berth')], max_length=100),
        ),
    ]
