# Generated by Django 4.2.20 on 2025-03-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_tripitem_is_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripdetail',
            old_name='trip_date',
            new_name='trip_start_date',
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='trip_end_date',
            field=models.DateField(null=True),
        ),
    ]
