# Generated by Django 4.2.20 on 2025-03-28 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0007_rename_trip_date_tripdetail_trip_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoprest',
            name='trip_detail',
        ),
        migrations.RemoveField(
            model_name='tripitem',
            name='trip_detail',
        ),
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField()),
                ('mileage_covered', models.FloatField(default=0)),
                ('is_current', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('trip_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logbook.tripdetail')),
            ],
        ),
        migrations.AddField(
            model_name='stoprest',
            name='trip_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logbook.tripday'),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='trip_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logbook.tripday'),
        ),
    ]
