# Generated by Django 4.2.20 on 2025-03-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0008_remove_stoprest_trip_detail_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tripday',
            unique_together={('trip_detail', 'trip_date')},
        ),
    ]
