# Generated by Django 4.2.20 on 2025-03-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0009_alter_tripday_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripday',
            old_name='mileage_covered',
            new_name='mileage_covered_today',
        ),
        migrations.AddField(
            model_name='tripday',
            name='total_miles_driving_today',
            field=models.FloatField(default=0),
        ),
    ]
