# Generated by Django 4.2.20 on 2025-03-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0010_rename_mileage_covered_tripday_mileage_covered_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripday',
            name='truck_trailer_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
