# Generated by Django 4.2.20 on 2025-03-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='driver_initials',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='driver_number',
            field=models.CharField(db_collation='case_insensitive', max_length=100, unique=True),
        ),
    ]
