# Generated by Django 4.2.20 on 2025-03-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_driver_initials_alter_user_driver_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='truck_trailer_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
