# Generated by Django 4.2.20 on 2025-04-01 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0012_carrier_remove_tripday_truck_trailer_number_truck_and_more'),
        ('users', '0003_user_truck_trailer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='truck_trailer_number',
        ),
        migrations.AddField(
            model_name='user',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logbook.carrier'),
        ),
    ]
