# Generated by Django 4.2.20 on 2025-04-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_truck_trailer_number_user_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_carrier_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
    ]
