# Generated by Django 4.2.20 on 2025-04-01 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0013_alter_carrier_admin'),
        ('users', '0005_user_is_carrier_admin_user_is_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logbook.carrier'),
        ),
    ]
