# Generated by Django 4.2.20 on 2025-04-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_driver_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='driver_number',
            field=models.CharField(blank=True, db_collation='case_insensitive', max_length=100, null=True, unique=True),
        ),
    ]
